# Generated by Django 5.2.3 on 2025-06-15 17:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealthiq', '0002_metric_snapshot_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendinguser',
            options={},
        ),
        migrations.RenameField(
            model_name='pendinguser',
            old_name='date_requested',
            new_name='request_date',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='ninety_day_completed_assessments',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='ninety_day_completion_rate',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='ninety_day_total_assessments',
        ),
        migrations.RemoveField(
            model_name='metricsnapshot',
            name='total_assessments',
        ),
        migrations.RemoveField(
            model_name='pendinguser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='pendinguser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='pendinguser',
            name='review_date',
        ),
        migrations.RemoveField(
            model_name='pendinguser',
            name='review_notes',
        ),
        migrations.RemoveField(
            model_name='pendinguser',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='metricsnapshot',
            name='active_patients',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='metricsnapshot',
            name='capacity_utilization',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='metricsnapshot',
            name='completed_assessments',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='metricsnapshot',
            name='completion_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='metricsnapshot',
            name='discharged_patients',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='metricsnapshot',
            name='inactive_patients',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('evaluator', 'Evaluator'), ('viewer', 'Viewer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('evaluator', 'Evaluator'), ('viewer', 'Viewer')], max_length=20),
        ),
    ]
