# Generated by Django 5.2.3 on 2025-06-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealthiq', '0003_add_pendinguser_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricsnapshot',
            name='ninety_day_completed_assessments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='ninety_day_completion_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='ninety_day_total_assessments',
            field=models.IntegerField(default=0),
        ),
    ]
