# Generated by Django 5.2.3 on 2025-06-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealthiq', '0004_add_ninety_day_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
