# Generated by Django 5.2.3 on 2025-06-15 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealthiq', '0004_add_missing_fields'),
    ]

    operations = [
    ]
