# Generated by Django 5.1.7 on 2025-04-21 21:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealthiq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='incomplete_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='scheduled_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='audit',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('incomplete', 'Incomplete')], default='scheduled', max_length=20),
        ),
    ]
