# Generated by Django 5.1.7 on 2025-05-18 21:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealthiq', '0002_audit_incomplete_reason_audit_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='missed_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='scheduled_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
