# Generated by Django 5.1.7 on 2025-05-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealthiq', '0003_assessment_missed_reason_assessment_scheduled_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='incomplete_reason',
            new_name='missed_reason',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('missed', 'Missed')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='audit',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('missed', 'Missed')], default='scheduled', max_length=20),
        ),
    ]
