# Generated by Django 5.1.7 on 2025-05-19 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealthiq', '0004_rename_incomplete_reason_audit_missed_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentalhealthiq.assessmentcriteria'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
