# Generated by Django 5.1.7 on 2025-05-20 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealthiq', '0005_alter_assessment_assessment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='scheduled_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
