# Generated by Django 5.1.7 on 2025-05-20 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealthiq', '0006_alter_assessment_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='scheduled_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
