# Generated by Django 5.2.1 on 2025-05-31 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealthiq', '0007_alter_audit_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='primary_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_patients', to='mentalhealthiq.staffmember'),
        ),
    ]
