# Generated by Django 5.2.1 on 2025-06-03 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealthiq', '0008_patient_primary_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='primary_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_patients', to='mentalhealthiq.staffmember'),
        ),
    ]
